{% set name = "uarray" %}
{% set version = "0.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Quansight-Labs/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 6a3de79506f223dc8e89f74b75895b32825cd6fed128b35907478cb49ff9f75f

build:
  number: 1
  skip: true  # [py<35]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - uarray

about:
  home: http://github.com/Quansight-Labs/uarray
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A backend-dispatch mechanism for Python.

  description: |
    `unumpy` is a backend-dispatch mechanism for Python.
  doc_url: http://uarray.readthedocs.io/
  dev_url: https://github.com/Quansight-Labs/uarray

extra:
  recipe-maintainers:
    - hameerabbasi
