{% set name = "uarray" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Quansight-Labs/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 5148dc8b2bba712e02504b12f8886292536689d53bc4ea4de3cd6b3fc11ef29b

build:
  number: 1
  skip: True  # [py<35]
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - uarray

about:
  home: http://github.com/Quansight-Labs/uarray
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A backend-dispatch mechanism for Python.'

  description: |
    `unumpy` is a backend-dispatch mechanism for Python.
  doc_url: http://uarray.readthedocs.io/
  dev_url: https://github.com/Quansight-Labs/uarray

extra:
  recipe-maintainers:
    - hameerabbasi
