{% set name = "uarray" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Quansight-Labs/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 9421f4efac62aa1db1fda97b764870eccfbd62f9f8d593c0a4f1472a98cb5c0b

build:
  number: 0
  skip: True  # [py<35]
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - uarray

about:
  home: http://github.com/Quansight-Labs/uarray
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A backend-dispatch mechanism for Python.'

  description: |
    `unumpy` is a backend-dispatch mechanism for Python.
  doc_url: http://uarray.readthedocs.io/
  dev_url: https://github.com/Quansight-Labs/uarray

extra:
  recipe-maintainers:
    - hameerabbasi
