# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
context:
  name: uarray
  version: 0.9.2

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 1e07c2bb99ac5aeb1db95bc7aae6bab94c69ce9d2bd388c2e58b136e29ed3ba4

build:
  number: 0
  script: python -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - if: build_platform != target_platform
      then:
      - python
      - cross-python_${{ target_platform }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - cmake >=3.15
    - if: not win
      then:
      - ninja
  host:
    - python
    - setuptools >=64
    - setuptools-scm >=8
    - pip
    - scikit-build-core >=0.10.0
  run:
    - python

tests:
  - python:
      imports:
        - uarray
  - requirements:
      run:
        - pip
    script:
      - pip check

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A backend-dispatch mechanism for Python.
  description: |
    `uarray` is a backend-dispatch mechanism for Python.
  homepage: https://github.com/Quansight-Labs/uarray
  repository: https://github.com/Quansight-Labs/uarray
  documentation: http://uarray.readthedocs.io/

extra:
  recipe-maintainers:
    - hameerabbasi
